
title: Daniel Wu's Resume
url: 'wuhangchen2279.github.io'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Daniel Wu
tagline: Software Developer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: wuhangchen2279@gmail.com
phone: (+61) 451018880
website: wuhangchen2279.github.io #do not add http://
linkedin: hangchen-daniel-wu-37a3aa89
github: wuhangchen2279
twitter: '@wuhangchen2279'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
